### ISSUE TITLE
run 

### ISSUE THREAD

**Issue by raminrzdh** [ricardobranco777/docker-volumes.sh#2]
when run sh file show error : 

docker-volumes.sh: 14: docker-volumes.sh: [[: not found
docker-volumes.sh: 14: docker-volumes.sh: dockermagento2_web_1: not found
docker-volumes.sh: 19: docker-volumes.sh: Syntax error: "(" unexpected (expecting "then")

**Comment by ricardobranco777** [comment]
On Debian based distributions, `sh` is not Bash, but Dash, which is an implementation of the POSIX Bourne shell that doesn't support `[[`.

You should run instead `bash docker-volumes.sh` or `chmod +x docker-volumes.sh ; ./docker-volumes.sh`.
