### ISSUE TITLE
Is Docker version 18.09-9 supported ?

### ISSUE THREAD

**Issue by mativillagra** [ricardobranco777/docker-volumes.sh#3]
Hi. 

I'm trying to use this great script but currently is not saving the volumes. 

Docker version 18.09.9-ce, build 039a7df on both instances. 

Steps:

1. 

`docker run -it --name http -d -p 9098:80 -v data-volume:/usr/local/apache2/htdocs httpd:2.4`

2. 

`docker inspect -f '{{ .Mounts }}' http
[{volume data-volume /var/lib/docker/volumes/data-volume/_data /usr/local/apache2/htdocs local z true }]`

3. 

`docker stop 6d70038e617b`

`docker commit 6d70038e617b web`

`docker save -o web.tar web`

`docker-volume.sh 6d70038e617b save web_volumes.tar`

4. 

Switch to another host/machine 

`docker load -i web.tar`

`docker create -p 9098:80  --name  web web`

`docker-volumes.sh -v web load web_volume.tar`

`usr/local/apache2/htdocs/`
`usr/local/apache2/htdocs/index.html`

`docker start web`

`docker inspect -f '{{ .Mounts }}' web
[]
`

The volumes is not loaded. Any help is appreciate. 

Thanks in advance.

**Comment by ricardobranco777** [comment]
The `/usr/local/apache2/htdocs` directory is not declared as a `VOLUME` in the Apache image. Apache should ship their Docker image with `VOLUME`'s declared just as Nginx does:
https://github.com/dockerfile/nginx/blob/master/Dockerfile

A quick fix is to do it yourself in step 3 like this:

`docker commit --change 'VOLUME /usr/local/apache2/htdocs' http web`

So I must enhance the documentation to clearly state that only volumes defined as such in the Docker image via `VOLUME` directives are supported.

**Comment by ricardobranco777** [comment]
Updated the description under the section `Bugs / Features`. 

Thanks for reporting!

**Comment by mativillagra** [comment]
@ricardobranco777 Great & quick explanation/comments!!  Thanks I will give this a try right away. 

Thanks in advance!
