### ISSUE TITLE
can i use this sh file to migrate docker container,image and volume from ubuntu 20 to windows 10?

### ISSUE THREAD

**Issue by lovelyplanet2019** [ricardobranco777/docker-volumes.sh#4]
I save the container and volume following your guide

Then, at windows 10 cmd

D:\test>docker create --name testimage1.tar testimage1
Unable to find image 'testimage1:latest' locally
Error response from daemon: pull access denied for testimage1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ricardobranco777** [comment]
The problem is not Docker but the different platform (OS & architecture).  If you use it with WSL it can work.

The `docker pull` fails because it can't find the image in the repository and you need to login first.
