### ISSUE TITLE
docker-volumes.sh command not found

### ISSUE THREAD

**Issue by tahami4444** [ricardobranco777/docker-volumes.sh#5]
I am trying your script and it give me error **docker-volumes.sh** command not found
and do let me know what to used instead of this **$USER@$HOST** I mean username and host IP of other host machine or simply as it is  ??

**Comment by ricardobranco777** [comment]
> doker-volumes.sh command not found

This is a typo.  It must be `docker-volumes.sh`.

> and do let me know what to used instead of this **$USER@$HOST**  I mean username and host IP of other host machine or simply as it is ??

You're right: username and host IP of other host machine.

**Comment by tahami4444** [comment]
It was corrected already but even then it shows same error

![image](https://user-images.githubusercontent.com/58389064/202143019-2c309f4d-489d-4d45-9a93-188e2e76b541.png)

**Comment by ricardobranco777** [comment]
> It was corrected already but even then it shows same error
> 
> ![image](https://user-images.githubusercontent.com/58389064/202143019-2c309f4d-489d-4d45-9a93-188e2e76b541.png)

Please specify the full path the script.
