### ISSUE TITLE
[Feature] Show remaining free space on server

### ISSUE THREAD

**Issue by mbabic84** [ricardobranco777/docker-volumes.sh#6]
Hi, qBittorent and some others has feature, which shows free space in status bar. Whould it be posible to implement something like this? Its quite handy.

![image](https://github.com/ricardobranco777/docker-volumes.sh/assets/17003448/d10ed047-0155-42af-b462-cd4e15813ebf)

Thank you.

**Comment by ricardobranco777** [comment]
> Hi, qBittorent and some others has feature, which shows free space in status bar. Whould it be posible to implement something like this? Its quite handy.
> 
> ![image](https://user-images.githubusercontent.com/17003448/256995153-d10ed047-0155-42af-b462-cd4e15813ebf.png)
> 
> Thank you.

Are you sure this is the correct project for that feature?

**Comment by mbabic84** [comment]
Heh, sorry, no it is not. I somehow skip to wrong repository.
