### ISSUE TITLE
Should only backup mouts with type volume

### ISSUE THREAD

**Issue by elpredatoro** [ricardobranco777/docker-volumes.sh#7]
I think script should only backup mounts with type: "volume", and not e.g. "bind". or add option to do so.

**Comment by ricardobranco777** [comment]
> I think script should only backup mounts with type: "volume", and not e.g. "bind". or add option to do so.

You're probably right. I'll add these options but the default behaviour shall remain.

**Comment by ricardobranco777** [comment]
Can you please test https://github.com/ricardobranco777/docker-volumes.sh/blob/options/docker-volumes.sh ?

**Comment by elpredatoro** [comment]
FILTER_BOTH='{{ range .Mounts }}{{ if eq .Type "bind" }}{{ printf "%v\x00" .Destination }}{{ else }}{{ printf "%v\x00" .Destination }}{{ end }}{{ end }}'
FILTER_BIND='{{ range .Mounts }}{{ if eq .Type "bind" }}{{ printf "%v\x00" .Destination }}{{ end }}{{ end }}'
FILTER_VOLUME='{{ range .Mounts }}{{ if eq .Type "volume" }}{{ printf "%v\x00" .Destination }}{{ end }}{{ end }}'

I think this works fine.

**Comment by ricardobranco777** [comment]
> `FILTER_BOTH='{{ range .Mounts }}{{ if eq .Type "bind" }}{{ printf "%v\x00" .Destination }}{{ else }}{{ printf "%v\x00" .Destination }}{{ end }}{{ end }}' 

The `if/else` is redundant in FILTER_BOTH.

**Comment by elpredatoro** [comment]
Yes. It should be as it was before changes.

**Comment by ricardobranco777** [comment]
Fixed, thanks!

**Comment by elpredatoro** [comment]
FILTER_BIND & FILTER_VOLUME should have one more "{{ end }}" ?

**Comment by ricardobranco777** [comment]
> FILTER_BIND & FILTER_VOLUME should have one more "{{ end }}" ?

Good catch. Fixed!
